# Generated by Django 5.0.2 on 2025-12-02 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliniturn_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('edificio', models.CharField(max_length=100)),
                ('piso', models.CharField(blank=True, max_length=50, null=True)),
                ('numero', models.CharField(max_length=50)),
                ('disponible', models.BooleanField(default=True)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='expedienteclinico',
            old_name='diagnostico_principal',
            new_name='diagnosticos',
        ),
        migrations.RemoveField(
            model_name='especialidad',
            name='clave',
        ),
        migrations.AddField(
            model_name='cita',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliniturn_api.especialidad'),
        ),
        migrations.AddField(
            model_name='expedienteclinico',
            name='tratamiento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='dias_atencion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='departamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='clave_admin',
            field=models.CharField(default='ADMIN_DEFAULT', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrador',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Atendida', 'Atendida'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='consultorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliniturn_api.consultorio'),
        ),
        migrations.AddField(
            model_name='medico',
            name='consultorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliniturn_api.consultorio'),
        ),
    ]
