# Generated by Django 5.0.2 on 2025-12-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliniturn_api', '0002_consultorio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
    ]
